# Generated by Django 5.2.5 on 2025-08-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('interior_type', models.CharField(choices=[('Living Room', 'Living Room'), ('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Office', 'Office'), ('Bathroom', 'Bathroom'), ('Dining Area', 'Dining Area'), ('Commercial Space', 'Commercial Space'), ('Other', 'Other')], max_length=50)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('completion_date', models.DateField()),
                ('image1', models.ImageField(upload_to='interior_works/', verbose_name='Main Image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='interior_works/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='interior_works/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='interior_works/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='interior_works/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
