# Generated by Django 5.2.5 on 2025-08-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Living Room', 'Living Room'), ('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Office', 'Office'), ('Bathroom', 'Bathroom'), ('Dining Area', 'Dining Area'), ('Commercial Space', 'Commercial Space'), ('Other', 'Other')], max_length=50)),
                ('short_description', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=100)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
