# Generated by Django 5.1.4 on 2025-08-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_featured_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Banner_image/')),
            ],
        ),
    ]
