# Generated by Django 5.1.4 on 2025-08-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_image',
            name='title',
            field=models.CharField(default='Elegant Interior Designs for Modern Living', max_length=200),
            preserve_default=False,
        ),
    ]
