# Generated by Django 5.1.4 on 2025-08-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_banner_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_image',
            name='descrition',
            field=models.CharField(default='Transform your home or office with our bespoke solutions, tailored to your lifestyle and taste.', max_length=200),
            preserve_default=False,
        ),
    ]
