# Generated by Django 5.1.4 on 2025-08-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_banner_image_descrition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner_image',
            old_name='descrition',
            new_name='description',
        ),
    ]
