# Generated by Django 5.1.4 on 2025-09-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Sliding Wardrobe', 'Sliding Wardrobe'), ('Media Wall', 'Media Wall'), ('Fitted Wardrobe', 'Fitted Wardrobe'), ('Fitted Kitchens', 'Fitted Kitchens'), ('Loft Wardrobes', 'Loft Wardrobes'), ('Home\xa0Office', 'Home\xa0Office'), ('Living Room', 'Living Room'), ('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Office', 'Office'), ('Bathroom', 'Bathroom'), ('Dining Area', 'Dining Area'), ('Commercial Space', 'Commercial Space')], max_length=50),
        ),
        migrations.AlterField(
            model_name='featured_blog',
            name='category',
            field=models.CharField(choices=[('Sliding Wardrobe', 'Sliding Wardrobe'), ('Media Wall', 'Media Wall'), ('Fitted Wardrobe', 'Fitted Wardrobe'), ('Fitted Kitchens', 'Fitted Kitchens'), ('Loft Wardrobes', 'Loft Wardrobes'), ('Home\xa0Office', 'Home\xa0Office'), ('Living Room', 'Living Room'), ('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Office', 'Office'), ('Bathroom', 'Bathroom'), ('Dining Area', 'Dining Area'), ('Commercial Space', 'Commercial Space')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interiorwork',
            name='interior_type',
            field=models.CharField(choices=[('Sliding Wardrobe', 'Sliding Wardrobe'), ('Media Wall', 'Media Wall'), ('Fitted Wardrobe', 'Fitted Wardrobe'), ('Fitted Kitchens', 'Fitted Kitchens'), ('Loft Wardrobes', 'Loft Wardrobes'), ('Home\xa0Office', 'Home\xa0Office'), ('Living Room', 'Living Room'), ('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Office', 'Office'), ('Bathroom', 'Bathroom'), ('Dining Area', 'Dining Area'), ('Commercial Space', 'Commercial Space')], max_length=50),
        ),
    ]
